version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: app
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    ports: ["6379:6379"]
    volumes: ["redisdata:/data"]

  api:
    build: ../api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/app
      REDIS_URL: redis://redis:6379
      EVOLUTION_BASE_URL: http://host.docker.internal:4000
      EVOLUTION_API_KEY: dev
    depends_on: [postgres, redis]
    ports: ["3001:3001"]

  worker:
    build: ../worker
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/app
      REDIS_URL: redis://redis:6379
      EVOLUTION_BASE_URL: http://host.docker.internal:4000
      EVOLUTION_API_KEY: dev
    depends_on: [postgres, redis, api]

  frontend:
    build: ../frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    depends_on: [api]
    ports: ["3000:3000"]

volumes:
  pgdata:
  redisdata: